services:
  redis:
    image: redis:8.0-alpine
    container_name: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 3
  gateway:
    build:
      context: ./src/services/gateway-service
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
    command: pnpm run start:dev
    depends_on:
      auth:
        condition: service_healthy
      user:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - app-network
  auth:
    build:
      context: ./src/services/auth-service
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - ./src/services/auth-service/.env
    command: pnpm run start:dev
    depends_on:
      postgres-auth:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8081/health']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - app-network
  user:
    build:
      context: ./src/services/user-service
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - ./src/services/user-service/.env
    command: pnpm run start:dev
    depends_on:
      postgres-user:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8082/health']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - app-network
  postgres-auth:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d auth_db']
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - app-network
  postgres-user:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d user_db']
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - app-network
volumes:
  postgres_auth_data:
  postgres_user_data:
networks:
  app-network:
    driver: bridge
